# Generated by Django 5.2.8 on 2025-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completado', models.BooleanField(default=False)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('tiempo_visto', models.PositiveIntegerField(default=0, help_text='Tiempo visto en segundos')),
            ],
            options={
                'verbose_name': 'Progreso de Sección',
                'verbose_name_plural': 'Progreso de Secciones',
                'db_table': 'progreso_secciones',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la sección')),
                ('contenido', models.TextField(verbose_name='Contenido de texto')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del video')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='secciones/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('duracion_minutos', models.PositiveIntegerField(default=0, help_text='Duración en minutos')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'db_table': 'secciones',
                'ordering': ['modulo', 'orden'],
            },
        ),
    ]
