# Generated by Django 5.2.8 on 2025-11-24 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modulos', '0001_initial'),
        ('secciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progresoseccion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='modulos.modulo'),
        ),
        migrations.AddField(
            model_name='progresoseccion',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secciones.seccion'),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('modulo', 'orden')},
        ),
        migrations.AlterUniqueTogether(
            name='progresoseccion',
            unique_together={('usuario', 'seccion')},
        ),
    ]
