# Generated by Django 5.2.8 on 2026-01-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='es_preview',
            field=models.BooleanField(default=False, help_text='Si es True, la sección es pública como vista previa'),
        ),
    ]
