# Generated by Django 5.2.8 on 2026-01-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secciones', '0003_seccion_es_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion',
            name='video_file',
            field=models.FileField(blank=True, help_text='Sube un archivo MP4 aquí o usa video_url para YouTube', null=True, upload_to='videos/', verbose_name='Archivo de video MP4'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video (YouTube, etc)'),
        ),
    ]
