# Generated by Django 5.2.8 on 2025-11-24 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del aviso')),
                ('descripcion', models.TextField(verbose_name='Descripción del aviso')),
                ('tipo', models.CharField(choices=[('general', 'General'), ('curso', 'Relacionado con curso'), ('sistema', 'Sistema'), ('promocion', 'Promoción')], default='general', max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True, verbose_name='Comentarios adicionales')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
                'db_table': 'avisos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
