# Generated by Django 5.2.8 on 2026-01-30 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_alter_aviso_tipo'),
        ('avisos', '0002_initial'),
    ]

    operations = [
    ]
