# Generated by Django 5.2.8 on 2025-11-24 21:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('programacion', 'Programación'), ('diseño', 'Diseño'), ('marketing', 'Marketing'), ('negocios', 'Negocios'), ('idiomas', 'Idiomas'), ('musica', 'Música'), ('fotografia', 'Fotografía'), ('otros', 'Otros')], max_length=50)),
                ('nivel', models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
