# Generated by Django 5.2.8 on 2025-11-24 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'perfil': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_como_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
