# Generated by Django 5.2.8 on 2025-11-25 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil': 'instructor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_como_instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
